// <auto-generated />
namespace TrueFill.DemandCaptureDataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class TFX_2_02 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TFX_2_02));
        
        string IMigrationMetadata.Id
        {
            get { return "202107011403138_TFX_2_02"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
