// <auto-generated />
namespace TrueFill.DemandCaptureDataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class TFX_1_96 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TFX_1_96));
        
        string IMigrationMetadata.Id
        {
            get { return "202104030440247_TFX_1_96"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
