// <auto-generated />
namespace SiteFuel.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class Pricing_1_85 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Pricing_1_85));
        
        string IMigrationMetadata.Id
        {
            get { return "202010281332157_Pricing_1_85"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
