// <auto-generated />
namespace SiteFuel.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class pricing_1_78 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(pricing_1_78));
        
        string IMigrationMetadata.Id
        {
            get { return "202008130848432_pricing_1_78"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
