// <auto-generated />
namespace SiteFuel.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class _201 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_201));
        
        string IMigrationMetadata.Id
        {
            get { return "202106160651102_Pricing_2.08"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
