// <auto-generated />
namespace SiteFuel.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class SFX_2_24 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SFX_2_24));
        
        string IMigrationMetadata.Id
        {
            get { return "202205090905278_SFX_2_24"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
