using SiteFuel.Exchange.Utilities;
using System;

namespace SiteFuel.Exchange.ViewModels
{
    public class UspGetSupplierInvoiceDetails
    {
        public int Id { get; set; }
        public int InvoiceHeaderId { get; set; }
        public int InvoiceVersionStatusId { get; set; }
        public string DisplayInvoiceNumber { get; set; }
        public string ReferenceId { get; set; }
        public int? OrderId { get; set; }
        public int InvoiceTypeId { get; set; }
        public int? ParentId { get; set; }
        public bool? IsHidePricingEnabledForBuyer { get; set; }
        public bool? IsHidePricingEnabledForSupplier { get; set; }
        public decimal DroppedGallons { get; set; }
        public decimal PricePerGallon { get; set; }
        public decimal StateTax { get; set; }
        public decimal FedTax { get; set; }
        public decimal SalesTax { get; set; }
        public decimal BasicAmount { get; set; }
        public decimal TotalFeeAmount { get; set; }
        public DateTimeOffset PaymentDueDate { get; set; }
        public DateTimeOffset? PaymentDate { get; set; }
        public int StatusId { get; set; }
        public int DDTConversionReason { get; set; }
        public int? CityGroupTerminalId { get; set; }
        public DateTimeOffset CreatedDate { get; set; }
        public int PaymentTermId { get; set; }
        public int NetDays { get; set; }
        public string Notes { get; set; }
        public decimal TotalTaxAmount { get; set; }
        public decimal TotalDiscountAmount { get; set; }
        public int WaitingFor { get; set; }
        public bool IsBuyPriceInvoice { get; set; }
        public Currency Currency { get; set; }
        public UoM UoM { get; set; }
        public bool? IsApprovalWorkflowEnabled { get; set; }
        public bool IsPendingInvoiceAdjustment { get; set; }
        public string PoNumber { get; set; }
        public int? ImageId { get; set; }
        public string ImagePath { get; set; }
        public int? BuyerCompanyId { get; set; }
        public int? SignImageId { get; set; }
        public string CustomerSignaturePath { get; set; }
        public int? FuelRequestTypeId { get; set; }
        public string DriverComment { get; set; }
        public int? LinkedInvoiceId { get; set; }
        public int? LinkedInvoiceType { get; set; }
        public string LinkedInvoiceNumber { get; set; }
        public string NonStandardFuelDescription { get; set; }
        public int? FuelDisplayGroupId { get; set; }
        public decimal? MaxQuantity { get; set; }
        public decimal? BrokeredMaxQuantity { get; set; }
        public int? QuantityTypeId { get; set; }
        public UoM FuelQuantityUoM { get; set; }
        public int? PricingTypeId { get; set; }
        public string CityGroupTerminalName { get; set; }
        public decimal? RequestPricePerGallon { get; set; }
        public decimal? RackPrice { get; set; }
        public PaymentMethods PaymentMethod { get; set; }
        public int? OrderTypeId { get; set; }
        public string BolNumber { get; set; }
        public string LiftTicketNumber { get; set; }
        public decimal? NetQuantity { get; set; }
        public decimal? GrossQuantity { get; set; }
        public decimal? LiftQuantity { get; set; }
        public decimal? DeliveredQuantity { get; set; }
        public DateTimeOffset? LiftDate { get; set; }
        public string Carrier { get; set; }
        public bool IsLiftFileValidated { get; set; }
        public int? BolImageId { get; set; }
        public string BolFilePath { get; set; }

        public string CreditCheckApprovalFilePath { get; set; }
        public int? AdditionalImageId { get; set; }
        public string AdditionalImgFilePath { get; set; }
        public bool? IsPublicRequest { get; set; }
        public int? DeliveryTypeId { get; set; }
        public DateTimeOffset? ScheduleDate { get; set; }
        public TimeSpan? StartTime { get; set; }
        public TimeSpan? EndTime { get; set; }
        public decimal? Quantity { get; set; }
        public string ExternalBrokerName { get; set; }
        public bool IsBuyAndSellOrder { get; set; }
        public int? ApprovalUserId { get; set; }
        public string FilePath { get; set; }
        public decimal? BrokerMarkUp { get; set; }
        public decimal? SupplierMarkUp { get; set; }
        public string TimeZoneName { get; set; }
        public bool? IsTaxExempted { get; set; }
        public int ExternalBrokerId { get; set; }
        public DateTimeOffset DropStartDate { get; set; }
        public DateTimeOffset DropEndDate { get; set; }
        public string DriverName { get; set; }
        public int? SupplierPreferredInvoiceTypeId { get; set; }
        public string TerminalName { get; set; }
        public decimal? TerminalLatitude { get; set; }
        public decimal? TerminalLongitude { get; set; }
        public decimal? JobLatitude { get; set; }
        public decimal? JobLongitude { get; set; }
        public string Signatory { get; set; }
        public bool? SignatoryAvailable { get; set; }
        public string StatusName { get; set; }
        public int AssetFilled { get; set; }
        public string SplitLoadChainId { get; set; }
        public int? SignatureId { get; set; }
        public int? AcceptedCompanyId { get; set; }
        public int? TerminalId { get; set; }
        public int? TrackableScheduleId { get; set; }
        public string FuelType { get; set; }
        public string CustomerEmail { get; set; }
        public string CustomerPhoneNumber { get; set; }
        public string CustomerName { get; set; }
        public string BuyerCompanyName { get; set; }
        public int? FuelRequestId { get; set; }
        public int AssetCount { get; set; }
        public int? FtlDetailId { get; set; }
        public int StatementId { get; set; }
        public string StatementNumber { get; set; }
        public bool SendDtnFile { get; set; }
        public string DisplayPrice { get; set; }
        public bool IsFtl { get; set; }
        public decimal AmountPaid { get; set; }
        public decimal BalanceRemaining { get; set; }
        public string InvoicePaidStatus { get; set; }
        public PaymentStatus PaymentStatus { get; set; }
        public int? OriginalInvoiceId { get; set; }
        public string OriginalInvoiceNumber { get; set; }
        public int? CreditInvoiceId { get; set; }
        public string CreditInvoiceDisplayNumber { get; set; }
        public CreationMethod CreationMethod { get; set; }
        public bool IsExceptionDdt { get; set; }
        public int RequestPriceDetailId { get; set; }
        public bool IsSingleBolInvoice { get; set; }
        public decimal TotalInvoiceAmount { get; set; }
        public int? PreferencesSettingId { get; set; }
        public bool IsSupressOrderPricing { get; set; }
        public string CarrierOrderId { get; set; }
        public string BrokeredChainId { get; set; }
        public bool IsMarineLocation { get; set; }
        public decimal? ConvertedQuantity { get; set; }
        public int? JobCountryId { get; set; }
        public int? CustomerId { get; set; }
        public bool IsBDNConfirmationRequired { get; set; }
        public bool IsInvoiceConfirmationRequired { get; set; }
        public string DeliveryLevelPO { get; set; }
        public string BDRNumber { get; set; }
        public TimeSpan? LiftStartTime { get; set; }

        public TimeSpan? LiftEndTime { get; set; }
    }
}
